2024-07-29 10:18:52,727 Start MPyC runtime v0.10
2024-07-29 10:18:52,798 All 3 parties connected.
2024-07-29 10:18:52,812 Stop MPyC -- elapsed time: 0:00:00.013|bytes sent: 4722
2024-07-29 10:18:55,097 Start MPyC runtime v0.10
2024-07-29 10:18:55,189 All 3 parties connected.
2024-07-29 10:18:55,213 Stop MPyC -- elapsed time: 0:00:00.023|bytes sent: 4722
2024-07-29 13:37:21,815 Start MPyC runtime v0.10
2024-07-29 13:37:21,910 All 3 parties connected.
2024-07-29 13:37:21,933 Stop MPyC -- elapsed time: 0:00:00.022|bytes sent: 4560
2024-07-29 14:23:00,480 Start MPyC runtime v0.10
2024-07-29 14:23:00,538 All 3 parties connected.
2024-07-29 14:23:00,560 Stop MPyC -- elapsed time: 0:00:00.022|bytes sent: 4560
2024-07-29 14:23:51,498 Start MPyC runtime v0.10
2024-07-29 14:23:51,579 All 3 parties connected.
2024-07-29 14:25:04,473 Start MPyC runtime v0.10
2024-07-29 14:25:04,553 All 3 parties connected.
2024-07-29 14:32:00,612 Start MPyC runtime v0.10
2024-07-29 14:32:00,683 All 3 parties connected.
2024-07-29 14:33:00,112 Start MPyC runtime v0.10
2024-07-29 14:33:00,191 All 3 parties connected.
2024-07-29 14:34:40,253 Start MPyC runtime v0.10
2024-07-29 14:34:40,348 All 3 parties connected.
2024-07-29 14:36:22,670 Start MPyC runtime v0.10
2024-07-29 14:36:22,740 All 3 parties connected.
2024-07-29 14:38:07,663 Start MPyC runtime v0.10
2024-07-29 14:38:07,731 All 3 parties connected.
2024-07-29 14:48:30,023 Start MPyC runtime v0.10
2024-07-29 14:48:30,113 All 3 parties connected.
2024-07-29 14:49:05,529 Start MPyC runtime v0.10
2024-07-29 14:49:05,620 All 3 parties connected.
2024-07-29 14:49:05,623 Exception in callback _SelectorSocketTransport._call_connection_lost(ConnectionRes...eset by peer'))
handle: <Handle _SelectorSocketTransport._call_connection_lost(ConnectionRes...eset by peer'))>
Traceback (most recent call last):
  File "/home/ania/anaconda3/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/ania/anaconda3/lib/python3.11/asyncio/selector_events.py", line 1117, in _call_connection_lost
    super()._call_connection_lost(exc)
  File "/home/ania/anaconda3/lib/python3.11/asyncio/selector_events.py", line 896, in _call_connection_lost
    self._protocol.connection_lost(exc)
  File "/home/ania/anaconda3/lib/python3.11/site-packages/mpyc/asyncoro.py", line 123, in connection_lost
    raise exc
  File "/home/ania/anaconda3/lib/python3.11/asyncio/selector_events.py", line 995, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
2024-07-29 14:49:47,462 Start MPyC runtime v0.10
2024-07-29 14:49:47,561 All 3 parties connected.
2024-07-29 17:16:33,365 Start MPyC runtime v0.10
2024-07-29 17:16:33,434 All 3 parties connected.
2024-07-29 17:16:33,458 Stop MPyC -- elapsed time: 0:00:00.023|bytes sent: 4560
